module.exports = {
  MIN_RADIO_OPTIONS: 1,
  MAX_RADIO_OPTIONS: 5,
  CHANGE_THRESHOLD: 2,
  FORM_NAME_MIN: 50,
  FORM_NAME_MAX: 15000,
  ROW_STYLES: '{normal^4|wrapped|inverse}',
  NUMBER_PER_ROW: '{1|2}',
  DEBUG_GENERATE_MANY_QUESTIONS: false
}